### ISSUE TITLE
Mine isn't working

### ISSUE THREAD

**Issue by whitelightning99** [Blu3wolf/HARDmod#38]
I first put the HardMod only in my mod section of the factorio and launched the game it launched but when i went to enable the mod the text was red. I looked at why and it said that Treefarm-lite, Treefarm-Ac, and bobslibrary were not downloaded. So i downloaded them and put them in the folder but when i tried to launch the game it said that there was an error with bobs modules which i had not downloaded. Then i downloaded that mod and put it in the folder but when i launched the game it says that there was an issue with bobs plates so i downloaded all of the mods labled bob. But when i went to launch the game it says that there is an error with bob's library and that it dose not match #1. But when i remove bob's library the game launches fine but all of the mods are in red and i cannot use them. I have tried everything and i have tried only downloading the mods that are in the read me but i am not very good at fixing issues with files and i want to play this mod but i cannot so please help.

**Comment by Blu3wolf** [comment]
In the mods menu, clicking each red mod will display an info bar on the right, which should explain why the mod is disabled. Chances are you dont have the same version of one of the mods as HARDmod is expecting.

**Comment by Blu3wolf** [comment]
As per the readme, you want to have bobs plates and bobs modules disabled, but installed, and you want treefarm lite and AC, and bobs library, installed and enabled.

**Comment by whitelightning99** [comment]
it is working now so thank you.
